### ISSUE TITLE
Support for dnd5e (request)

### ISSUE THREAD

**Issue by StevenEvans1966** [BernhardPosselt/pf2e-kingmaker-tools#15]
I am starting the kingmaker campaign and am looking to use you code for the kingdom management.  This should be possible as running the kingdom is a self contained system.  

The main issue here is how to make the structure actors.

I am thinking making kingdom management into separate module from the other macro areas would be the best solution.

**Comment by BernhardPosselt** [comment]
Go for a separate module. I'll likely not do armies because it will be merged into the 2e system soon enough so that I won't encounter it. 

I've already looked at the V11 beta where you can do custom actors in modules, but TypeScript support is so bad that I'm not sure how to procede.

**Comment by BernhardPosselt** [comment]
Closing this one. If you want to make it work for 5e, I recommend to fork my module. ATM the kingdom sheet depends on 2e actors because Foundry, so you can't make it compatible for both systems at once.
