### ISSUE TITLE
support for translation(request)

### ISSUE THREAD

**Issue by NaricaNardica** [BernhardPosselt/pf2e-kingmaker-tools#17]
Greetings!
I'm a FVTT user from China and I'm playing KM2. Your module has helped us a lot to deal with the Kingdom systems.
However, one of my teammates wants a translation for this mod so I want to translate it into Chinese(zhCN).
Could you provide a opportunity for localization? 

I am not a native speaker so if my request is unclear please let me know.
Best wishes!

**Comment by sakusenerio** [comment]
Wish the same thing here. 

If we‘re allowed to do localization work,  would you plz consider put the project on weblate? 
https://weblate.foundryvtt-hub.com/

Plz take a look. It should be easier to set up and much friendly on following up.

**Comment by BernhardPosselt** [comment]
Thanks for the request, however since support in core will come out later this year and translating the code base is a quite difficult, multi-day effort, I'm not gonna invest time into this.

**Comment by BernhardPosselt** [comment]
I was able to implement translations in the rewrite. See https://github.com/BernhardPosselt/pf2e-kingmaker-tools?tab=readme-ov-file#translations if you want to help translating the module.
