### ISSUE TITLE
Allow modification of weather DCs

### ISSUE THREAD

**Issue by Mathiam17** [BernhardPosselt/pf2e-kingmaker-tools#19]
The precipitation and temperature DCs change depending on which season/month it is. The actual DCs can be found in the links below:
- Precipitation https://2e.aonprd.com/Rules.aspx?ID=1900
- Temperature https://2e.aonprd.com/Rules.aspx?ID=1901

A possible solution is to add another integer field for custom DCs [for precipitation and temperature separately] in the game settings (this would be the easiest solution)

The other [more complex] solution is to base the DCs on seasons and months that are found in Foundry but this is way too complex

**Comment by BernhardPosselt** [comment]
> The other [more complex] solution is to base the DCs on seasons and months that are found in Foundry but this is way too complex

It's already using the built in internal time.
