### ISSUE TITLE
Issues installing

### ISSUE THREAD

**Issue by Tyrim** [BernhardPosselt/pf2e-kingmaker-tools#22]
When clicking Install in the module browser, I get an error:
![image](https://github.com/BernhardPosselt/pf2e-kingmaker-tools/assets/15132890/264cdc55-eff1-4ff0-ab86-08c27fd39b36)

**Comment by BernhardPosselt** [comment]
Are you on Forge? If so, try again now and in the following days until you get their latest build.

**Comment by Tyrim** [comment]
Not on the Forge, but I'll try again soon. Thanks!

**Comment by BernhardPosselt** [comment]
Are you on V11?

**Comment by Tyrim** [comment]
Not quite yet. Is that going to be the difference?

**Comment by BernhardPosselt** [comment]
Yes, your current install points to a newer manifest

**Comment by BernhardPosselt** [comment]
I hope this issue is fixed on newer installs based on some dev feedback, but I'm not sure if your version simply caches the old stuff.
