### ISSUE TITLE
Cloning repository makes the module break

### ISSUE THREAD

**Issue by Longstrider** [BernhardPosselt/pf2e-kingmaker-tools#23]
Hi Bernhard!
I was trying to tweak some things in your amazing module (thank you again for your hard work!), but when I clone it, install yarn and run it (without any changes), I can only see Custom Journals and Custom Rolltables in the Kingmaker Tools folder - and both of them are empty. 

On the other hand, when I install it through the Foundry menu it works just fine. Any ideas on what may cause this issue? Thanks in advance!

Foundry v11.304
PF2 v5.1.0

![FVTT Kingmaker Tools](https://github.com/BernhardPosselt/pf2e-kingmaker-tools/assets/115902273/d93ae569-6b19-4d19-9e51-6fd0df574370)
![Git-Yarn-Run](https://github.com/BernhardPosselt/pf2e-kingmaker-tools/assets/115902273/c6bae5b4-b43c-4247-a55f-92595c6125b8)

**Comment by BernhardPosselt** [comment]
Yeah, those include my non OGL content ;)

Try to exclude them from the module.json file here https://github.com/BernhardPosselt/pf2e-kingmaker-tools/blob/master/module.json#L97-L104 and here https://github.com/BernhardPosselt/pf2e-kingmaker-tools/blob/master/module.json#L127

**Comment by BernhardPosselt** [comment]
They are stripped out in the build process btw

**Comment by Longstrider** [comment]
> Yeah, those include my non OGL content ;)
> 
> Try to exclude them from the module.json file here https://github.com/BernhardPosselt/pf2e-kingmaker-tools/blob/master/module.json#L97-L104 and here https://github.com/BernhardPosselt/pf2e-kingmaker-tools/blob/master/module.json#L127

Hm, it does exclude them from the compendium, but doesn't make all the other stuff appear... Now "Kingmaker Tools" is a sad empty folder 😅

**Comment by BernhardPosselt** [comment]
Yeah, my impression was that having those compendia would just create them so I'm not 100% sure what's going on here.

**Comment by Longstrider** [comment]
> Got it, you need to run
> 
> ```
> yarn install
> yarn run build
> ```
> 
> and then for whatever reason restart Foundry. Removing the compendia is not required.

I've run those before, but I double-checked it now - still, only those two compendia can be found in-game. That's what Git Bash says:

![Yarn run](https://github.com/BernhardPosselt/pf2e-kingmaker-tools/assets/115902273/91d5dc77-bc86-4f77-b35e-9e40b8cbc4c4)

Should I maybe reinstall yarn, or clone the repo again? Or maybe some remaining temp files may cause the issue? Sorry to trouble you with it, and thanks for all your help! If there's no fast and easy solution - no problem, it's not that crucial for now.

**Comment by BernhardPosselt** [comment]
My guess is that there are some foundry temp files lying around or foundry is still running in the background

**Comment by BernhardPosselt** [comment]
Can you try running this inside a Linux VM?

**Comment by BernhardPosselt** [comment]
If you've still have trouble let me know and we can look at it on Discord if that's fine for you

**Comment by Longstrider** [comment]
> Can you try running this inside a Linux VM?

Sadly, I didn't manage to...



> If you've still have trouble let me know and we can look at it on Discord if that's fine for you

I'm gonna try some shenanigans that came to my mind and will let you know about the result. Thanks a lot for your readiness to help!
