### ISSUE TITLE
Assurance has unrest applied

### ISSUE THREAD

**Issue by jamesa-hutchins** [BernhardPosselt/pf2e-kingmaker-tools#24]
When using Kingdom assurance, the unrest penalty is applied to the role when it should not be.

Relevant rule - "Once per Kingdom turn, when you would attempt a skill check for that skill, you can forgo rolling and instead take a result equal to 10 + your proficiency bonus; do not apply any other bonuses, penalties, or modifiers to this result."

**Comment by BernhardPosselt** [comment]
Thank you for the report, will take a look
