### ISSUE TITLE
Using module locks the rain ambience on all scenes

### ISSUE THREAD

**Issue by NRschwier** [BernhardPosselt/pf2e-kingmaker-tools#27]
Using module locks the rain ambience on all scenes and makes it unchangable.

Foundry v11
PF2e v5.2.1

**Comment by BernhardPosselt** [comment]
Use the latest release and turn off weather.

**Comment by BernhardPosselt** [comment]
PS: I've just pushed an update that also lets you disable weather/playlist syncing on per-scene basis.
