### ISSUE TITLE
No camping sheet

### ISSUE THREAD

**Issue by Khybersghost** [BernhardPosselt/pf2e-kingmaker-tools#28]
Not getting any popup to create a camping sheet when I run any of the camping macros provided by the module.

**Comment by BernhardPosselt** [comment]
Any output using F12?

**Comment by Khybersghost** [comment]
I think I'm on 0.33 iirc? I'll have another look when I get a chance today. Also I'm using the Forge hosting service and I'm currently on v10.x for foundry. 

All I see is the image for the camping macro you linked

**Comment by BernhardPosselt** [comment]
Any red console output (F12) when you run the macro?

**Comment by Khybersghost** [comment]
Sorry for the late reply. I am running V10. I've updated my local to V11 to
test and it works fine.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
