### ISSUE TITLE
Quickly Create the Needed Tokens?

### ISSUE THREAD

**Issue by emckee2006** [BernhardPosselt/pf2e-kingmaker-tools#30]
I understand that you can't ship the tokens due to copyright reasons.  However, do you have any advice on how to quickly create them, perhaps in bulk?  I guess I can do them as I need them and slowly build up the directory.  I was just hoping there would be an easier route...

**Comment by BernhardPosselt** [comment]
No quick way, took me 2 days. Extract the tokens from the PDF using https://www.rptools.net/toolbox/token-tool/ then use your favorite way of creating the tokens

**Comment by Tyrim** [comment]
Where even do you get official tokens? Are they available anywhere for purchase?

**Comment by emckee2006** [comment]
I've been making mine from the pdf as needed...

**Comment by BernhardPosselt** [comment]
@Tyrim the official frames are shipped with the bestiary tokens module, you can use those to make the Kingmaker ones in Gimp, similar to this video https://www.youtube.com/watch?v=cZpERsXIjUc

**Comment by Tyrim** [comment]
> @Tyrim the official frames are shipped with the bestiary tokens module, you can use those to make the Kingmaker ones in Gimp, similar to this video https://www.youtube.com/watch?v=cZpERsXIjUc

That module is great, but I'm not sure how it relates to things like the thylacine and others that simply aren't there.

**Comment by BernhardPosselt** [comment]
Thylacine is in the PDF. You extract the image from the PDF, then use the token frame shipped in the module's directory.

**Comment by Tyrim** [comment]
> Thylacine is in the PDF. You extract the image from the PDF, then use the token frame shipped in the module's directory.

I see. Oof. Thanks.
