### ISSUE TITLE
Manage Button Not Populating Camping Sheet

### ISSUE THREAD

**Issue by mikedao** [BernhardPosselt/pf2e-kingmaker-tools#32]
Environment: 
* Foundry V11 Build 308
* PF2e system 5.4.1 and 5.4.2
* Tested on self hosted on an AWS EC2 instance and locally.

I can import the camping sheet using the macro and I've set the ownership, but the only Camping Activity that appears is Prepare Campsite. I have attempted to add additional ones by clicking the Manage button and upon doing so there are activities already checked in there, but nothing appears on the main camping sheet.

I have been able to reproduce this in a completely different environment (locally instead of prod on AWS) on brand new empty worlds in both, and locally I have reproduced this issue with the module being the only module installed.

**Comment by BernhardPosselt** [comment]
Roll prepare campsite or set the success and the remaining actions will show up ;)

**Comment by mikedao** [comment]
Aha! I think that did it, thank you so much, @BernhardPosselt. 

I think I didn't catch that because the roll buttons aren't working for me. Tried this in both of my environments, and I am getting this error in my JS console:

pf2e.mjs:27 Uncaught (in promise) TypeError: Cannot use 'in' operator to search for 'statistic' in 14
    at pf2e.mjs:27:230703
    at _StatisticCheck.roll (pf2e.mjs:27:231059)
    at _Statistic2.roll (pf2e.mjs:27:226877)
    at t.rollCampingCheck (camping.ts:146:44)
    at _.rollStandardCheck (sheet.ts:471:62)
    at _.rollCheck (sheet.ts:448:28)
    at async sheet.ts:386:42
    at async HTMLButtonElement.<anonymous> (utils.ts:177:49)

The number is 15 instead of 14 when I am trying it locally. Not a huge problem as I can just have players roll manually, or I can request the roll.

**Comment by BernhardPosselt** [comment]
Try to update to the latest version, the 2e system broke the module, 0.3.6 should fix that issue.

**Comment by mikedao** [comment]
That did the trick! I thought I had updated to your latest change but clearly I did not. Thank you so much for your help, this module is great and I'm also using your others!
