### ISSUE TITLE
Macros not working 9/2/2023

### ISSUE THREAD

**Issue by Crusher102** [BernhardPosselt/pf2e-kingmaker-tools#33]
I have just updated to 0.4.0 and I can't open any macros in my Hotbar, They are not in the Compendium anymore, I have tried to move it to 0.3.6 and 0.3.5 and I still don't see it.

**Comment by BernhardPosselt** [comment]
Which macros are we talking about? This is from my installation running the latest version from the registry.

![image](https://github.com/BernhardPosselt/pf2e-kingmaker-tools/assets/195053/6a6b83bb-0017-4a17-9f8f-6fb6fb945a2e)

**Comment by BernhardPosselt** [comment]
Are you on V10?

**Comment by LeChatLunatique** [comment]
I do have the same issue, there is nothing in the compendium folder.
![023b5721211d9a4409692ff5890fbdaa](https://github.com/BernhardPosselt/pf2e-kingmaker-tools/assets/143937578/f9367cf0-40b5-4e48-a462-b49c646a8ee6)
![65eee9c38d80664527fc22c0b7c86a9f](https://github.com/BernhardPosselt/pf2e-kingmaker-tools/assets/143937578/33c512b7-7cb4-4782-9720-b53888781714)

**Comment by BernhardPosselt** [comment]
Anything in the logs (F12)? Have you tried uninstalling and reinstalling the module? Using ForgeVTT?

Can't reproduce here unfortunately.

**Comment by Crusher102** [comment]
I have uninstalled it and reinstalled it, I also am on V11 (Build 307). This is what I get in the console when I try to open the macro in the hotbar. (I also use "The Forge" it was working before the 0.4.0 update but even if I go back it still not working)


![Screenshot 2023-09-03 150217](https://github.com/BernhardPosselt/pf2e-kingmaker-tools/assets/129578998/d7fe99ba-ebf6-4f91-abac-8d8f5dbe5626)

**Comment by BernhardPosselt** [comment]
Can you check if the module is disabled?

**Comment by Crusher102** [comment]
WOW, I can't believe that I missed that. 
![image](https://github.com/BernhardPosselt/pf2e-kingmaker-tools/assets/129578998/4f032a47-c100-49c7-b50b-cda2e1918fe5)
Ya that will do it

**Comment by Crusher102** [comment]
sorry about that XD

**Comment by Crusher102** [comment]
So it was on but it looks like it auto-turned off because of this 
![image](https://github.com/BernhardPosselt/pf2e-kingmaker-tools/assets/129578998/2a4cb408-9df9-46b2-834f-c848ec5bcda4)
thanks for reminding me that was a thing.

**Comment by BernhardPosselt** [comment]
Yes, the 2e system broke their API so I had to hard require a new version.

**Comment by Crusher102** [comment]
got ya, thank you for the help!
