### ISSUE TITLE
Error when clicking 'Subsist' on the camp menu

### ISSUE THREAD

**Issue by Tyrim** [BernhardPosselt/pf2e-kingmaker-tools#34]
![image](https://github.com/BernhardPosselt/pf2e-kingmaker-tools/assets/15132890/8f281e21-e26a-4642-aa56-5958c0ef945b)

I am getting this error when clicking to roll 'Subsist' on the camp menu, and I'm not sure why. Any help would be appreciated!

**Comment by BernhardPosselt** [comment]
Update both the module and your pf2e version

**Comment by Tyrim** [comment]
They are up to date. PF2e version 5.4.3 and KM Tools 0.4.0.

**Comment by BernhardPosselt** [comment]
Is the module enabled?

**Comment by Tyrim** [comment]
It is.

**Comment by BernhardPosselt** [comment]
Ok, looks like another API break, one sec.

**Comment by BernhardPosselt** [comment]
Should be fixed in 0.4.1, thanks!

**Comment by Tyrim** [comment]
Thank you! This mod is a lifesaver. Do you have a Patreon?

**Comment by BernhardPosselt** [comment]
Nope :) 

If you want to, you can gift me some paizo store credit at bernhard@posselt.at

**Comment by Tyrim** [comment]
What's your Paizo username? It won't let me do it by email address :)

**Comment by BernhardPosselt** [comment]
https://paizo.com/people/demlin I guess :)

**Comment by BernhardPosselt** [comment]
Many thanks :) will use that for the official Foundry modules so that's very generous :)

**Comment by Tyrim** [comment]
Thank you!
