### ISSUE TITLE
Elk compendium reference broken

### ISSUE THREAD

**Issue by Tyrim** [BernhardPosselt/pf2e-kingmaker-tools#36]
In the Rostland Hinterlands encounter table, the Elk result is a broken reference to an entry that doesn't exist.

**Comment by BernhardPosselt** [comment]
Elk has been removed from the Kingmaker bestiary and is only available through the QftFF one, that's why it's broken, thanks for the report

**Comment by BernhardPosselt** [comment]
Fixed.
