### ISSUE TITLE
Editing Recipes and other macros [Not really an issue]

### ISSUE THREAD

**Issue by Longstrider** [BernhardPosselt/pf2e-kingmaker-tools#4]
Hey!
Sorry to bother you through an issue - I found no other way to contact you. If I was to edit the recipes links in the macro, how would I do that? I know the basics, but the macro itself reads "game.pf2eKingmakerTools.macros.discoverSpecialMealMacro(actor)". I've found the template in the module's folder, but for the life of me I can't find where is the macro itself and how I can edit it - if it's possible only having the module files. If you could help, I'd really really appreciate it. Thank you for your hard work.

**Comment by BernhardPosselt** [comment]
First install git, nodejs and yarn, then follow: https://github.com/BernhardPosselt/pf2e-kingmaker-tools#git

You need to edit it in the source code right here https://github.com/BernhardPosselt/pf2e-kingmaker-tools/blob/master/src/camping.ts#L213 and run **yarn run build** a second time.

Regarding the uuid field, you can find that one in the rules section of the item 
![Screenshot from 2023-02-19 20-31-22](https://user-images.githubusercontent.com/195053/219970891-200ed236-c66d-4fa7-9de5-e5d0bd6e6ebe.png). You need to do this after every update for now.

Should be straight forward I hope?

**Comment by BernhardPosselt** [comment]
Macro is right here btw, although in TypeScript so not directly executable.

**Comment by Longstrider** [comment]
Yeah, I think I'll manage it. Thank you very much, you're truly a livesaver!

**Comment by BernhardPosselt** [comment]
I'll add something to make it configurable during the next week probably, too tired today ;) Will let you know in the ticket.

PS: I'm usually available on https://discord.com/invite/pf2e (putty)

**Comment by BernhardPosselt** [comment]
Added it and published it under 0.0.18

**Comment by Longstrider** [comment]
> Added it and published it under 0.0.18

Oh, that's so amazing! Greatly appreciate it!
