### ISSUE TITLE
Camping Sheet not working!

### ISSUE THREAD

**Issue by Neverrzz** [BernhardPosselt/pf2e-kingmaker-tools#42]
Hi, recent installer of your wonderful module. I cannot seem to get the Camping Macro to work! When I click on it as it recommends, I get this message in the console and nothing shows up. The Kingdom Sheet works just fine though! Hopefully you can assist in what is wrong, I assume it's on my end!
![image](https://github.com/BernhardPosselt/pf2e-kingmaker-tools/assets/146311802/29d82f29-609c-4272-a874-1a567bb9d51e)

**Comment by BernhardPosselt** [comment]
Can you delete the Camping Sheet actor and try again?
