### ISSUE TITLE
Camping wont allow for ingredients to be added

### ISSUE THREAD

**Issue by KaneFaolan** [BernhardPosselt/pf2e-kingmaker-tools#44]
I am trying to get this amazing tool working with the newly released kingmaker module.  Specifically i am trying to use the camping macro.  most of the features work, but when i roll for hunt and gather and get a number of ingredients, i cannot add them to my availably resources by pressing apply in the chat log.  when i press apply nothing happens.

I am running Foundry 11.309 and pathfinder 2e 5.6.1, and have version 0.5.0 of this module installed.  any help would be greatly appreciated, and again, amazing work on this!

**Comment by BernhardPosselt** [comment]
Anything in console log? Usually it will add it to the actor that was performing the action, but you can also override it in your sheet settings. Works here locally:

![image](https://github.com/BernhardPosselt/pf2e-kingmaker-tools/assets/195053/ca42fa74-c05b-41a1-b2a9-e78258ee1c49)

**Comment by KaneFaolan** [comment]
There is nothing obvious in the F12.  when i click on the apply button nothing is added to the f12 logs, it is almost as if it is not registering the click of the apply button.  see image below just after i clicked.

![image](https://github.com/BernhardPosselt/pf2e-kingmaker-tools/assets/146483740/40123f9c-1d0e-45d1-b1c5-a897610ef5db)

I was able to find something while looking further at your journal notes... it looks like the links to the ingredients are broken.  additionally, when i opened the journal, the error shown in the picture showed up in f12.

![image](https://github.com/BernhardPosselt/pf2e-kingmaker-tools/assets/146483740/2e0a240f-e388-4dad-96f4-64f8ff24317b)

**Comment by BernhardPosselt** [comment]
Will remove those links, those were merged into the core 2e system. Shouldn't break it though

**Comment by BernhardPosselt** [comment]
Can you disable all other modules and try again?

**Comment by KaneFaolan** [comment]
Looks like that fixed it.  i will try re-activating one at a time to find the culprit

**Comment by KaneFaolan** [comment]
Soooooo.... I have no idea... I slowly re-activated all my modules, and it still works find... Maybe it was an order of operations issue.

Thanks for the help, it is working now and i will cross my fingers it keeps working.

![image](https://github.com/BernhardPosselt/pf2e-kingmaker-tools/assets/146483740/a79ca0a5-a923-4dbe-bcc3-9dc66862f150)

**Comment by BernhardPosselt** [comment]
Great to hear, could have been a desync issue as well and the forced reload fixed it. Just pushed an update for better integration with the official module fyi

**Comment by BernhardPosselt** [comment]
I will publish a fix in the next few days for the broken links in the journal.

**Comment by KaneFaolan** [comment]
Thank you for all the help and for all your work on this amazing module. you are a god amongst men!
