### ISSUE TITLE
Kingdom Sheet Settlement Consumption not counted

### ISSUE THREAD

**Issue by Lucaken** [BernhardPosselt/pf2e-kingmaker-tools#46]
There are two settlements and two armies. Consumption on the sheet is saying 2. Armies have been placed using guidelines, deleting their tokens removes/adds consumption as intended. Both settlements are villages, they're on the sheet and have linked scenes, with only building actors in them. Adding or removing the settlements does not affect the Consumption count - tried removing the armies and then adding the settlements, and vice-versa, didn't change it.

Settlements linked, no army tokens in any scene:
![image](https://github.com/BernhardPosselt/pf2e-kingmaker-tools/assets/89641048/e9895ed0-ba49-4435-b0eb-b1afa5942d50)

Settlements linked, army tokens placed in one scene:
![image](https://github.com/BernhardPosselt/pf2e-kingmaker-tools/assets/89641048/4a78edf0-fbb1-47ae-b93a-37502a7869b3)

**Comment by BernhardPosselt** [comment]
Have you added buildings or farms on the sheet that reduce the consumption count? Consumption should be 2 without armies, tested locally:
![image](https://github.com/BernhardPosselt/pf2e-kingmaker-tools/assets/195053/b0ac2aa6-93ce-4cf7-a84d-db3263dc9ca3)

**Comment by Lucaken** [comment]
That was it. I didn't realize Farmlands directly reduced Consumption, I thought they produced Food. Makes a bit more sense. If there is space on the sheet, I'd be cool to have that noted somewhere on the sheet, if there is even space.

Thanks for the help, either way. Great module, I hope the premium module devs push for more integration with your tools.

**Comment by BernhardPosselt** [comment]
:+1:
