### ISSUE TITLE
implementation of more specific build structure activities

### ISSUE THREAD

**Issue by dharkus5000** [BernhardPosselt/pf2e-kingmaker-tools#51]
it'd be great if there was an automated drop-down on build a structure, so you can pick the building you're constructing

**Comment by BernhardPosselt** [comment]
Implementation should probably allow you to drag and drop a structure (or army for army activities) onto the modifier popup. 

Quite a bit of work, just a heads up.

**Comment by BernhardPosselt** [comment]
Forgot there was an issue :)
