### ISSUE TITLE
Cook Meal, No Options

### ISSUE THREAD

**Issue by Nuku** [BernhardPosselt/pf2e-kingmaker-tools#53]
No options are given for selecting a meal. Why is this and how can it be fixed?
![image](https://github.com/BernhardPosselt/pf2e-kingmaker-tools/assets/886729/f2458bd3-c5d2-4a17-bafc-86af9a44a4c5)

**Comment by BernhardPosselt** [comment]
Scroll down further, it's at the very end since RAW, you don't roll during the camping phase but during the eating one.
