### ISSUE TITLE
fame/infamy points do not reset at end of turn

### ISSUE THREAD

**Issue by dbavirt** [BernhardPosselt/pf2e-kingmaker-tools#62]
I did not realize it, but fame/infamy points are to reset at the end of each turn.  "All Fame/ Infamy points left unspent at the end of a Kingdom turn are lost."  Kingmaker p.537   The pf2e-kingmaker-tools kingdom sheet is not doing this, though it's doing lots of other housekeeping actions.

**Comment by BernhardPosselt** [comment]
Good catch, missed that.
