### ISSUE TITLE
Request: Add Optional Full Vance and Kerenshara Homebrew

### ISSUE THREAD

**Issue by digitalshadowhawk** [BernhardPosselt/pf2e-kingmaker-tools#64]
I'm just starting out running Kingmaker myself, and stumbled onto Vance and Kerenshara's Kingdom Building Homebrew. When I first found this module, I was ecstatic, as the module "includ[es] optional and popular homebrew from Vance & Kerenshara" which made me think I could run everything that way. Unfortunately after digging into the settings, while it does have some of the more popular solutions that they came up with, it doesn't have nearly all of them.

**Comment by BernhardPosselt** [comment]
What settings does it lack?

**Comment by BernhardPosselt** [comment]
Here's the list in the manual of what is supported:
![image](https://github.com/BernhardPosselt/pf2e-kingmaker-tools/assets/195053/4660daac-00ba-42de-bf8f-b68c80f65fab)

**Comment by digitalshadowhawk** [comment]
So most of what I was looking at was in the Analysis document, and I wasn't able to find the manual at first, but I'm going through now and double checking things (and "mapping" the names of solutions in the document to settings in your module for future GMs stumbling onto this)
Solution 1-1: More Trained Skills and Skill Increases - Kingdom Sheet Setting: Double Skill Increases
Solution 1-2: Untrained Improvisation - Kingdom Sheet Setting: Always Increase Untrained Skills by Half Level/Full Level (level 7)
Solution 1-3: More Ability Score Increases - _not an option, also not mentioned to be excluded in the manual, however it's simple enough to type in extra numbers_
Solution 1-4: Missing Item Bonuses - implemented in Structures marked with **V&K**
Solution 1-5: Allow Item Bonuses From Different Structures to Stack - Kingdom Sheet Setting: All Structures Item Bonuses Stack

Solution 2-1a: Capital Investment doesn't have the option for alternate requirements, specifically "You must be in the capital or..."
Solution 2-1b: Request Foreign Aid doesn't do the DC stacking, but that's mentioned in the manual.
Solution 2-2: New Activities - Reconnoiter Hex and Take Charge are implemented, just blacklisted by default. Uncheck these in the blacklist and you should be good to go.
Solution 2-3: More Social Opportunities - This is actually entirely on the GM to do. Come up with a list of groups for the kingdom to interact with and set DCs yourself.

Solution 3-1: Fixing the Status Bonus - As written, these rules would stack status bonuses, but the module changes them to circumstance bonuses, which works just as well
Solution 3-2: Fixing an OP Feat: Practical Magic - this one is specifically called out as not implemented but easy to do manually. The only thing to be aware of is that as the GM you have to make sure your players know you can't use Magic in place of Engineering, as the text is not edited/editable from the Kingdom Sheet.
Solution 3-3: Making Other Feats More Useful - Not actually an explicit solution, so can't be implemented.
Solution 3-4: New Kingdom Feats - also no content provided, so impossible to implement for everyone, but there's also nowhere to add homebrew ones (yet?)

Solution 4-1: More Milestones - This is implemented beautifully as a list that the players can read over and get ideas from. Just check the Vance and Kerenshara XP Rules option on the kingdom sheet settings
Solution 4-2: Increased XP from claiming hexes - also implemented by checking the previous setting on
Solution 4-3: Increased RP to XP Conversion - also implemented by checking the previous setting on

Solution 5-1: Allow the Capital to Grow Earlier - If this is implemented, I'm not sure how.
Solution 5-2: Increase the Influence of the Capital at the Lowest Levels - after manual editing of the capital on the kingdom sheet and inspecting the settlement, this does not appear to be implemented.


Now to respond to the actual comment thread, it seems the only ones that aren't either implemented or called out in the manual are the solutions for problem 5, which just happened to be the ones I was checking. The only other things I would request are the ability to homebrew new and existing kingdom feats, but I understand that may take a bit of work.

**Comment by BernhardPosselt** [comment]
> Solution 2-1a: Capital Investment doesn't have the option for alternate requirements, specifically "You must be in the capital or..."

You can create a special building in your capital, hide it and add the **enableCapitalInvestment: true** option using https://github.com/BernhardPosselt/pf2e-kingmaker-tools/blob/master/docs/structure-rules.md

Though not sure why anyone would want to use that rule though. It's possible though.

>  Solution 3-4: New Kingdom Feats - also no content provided, so impossible to implement for everyone, but there's also nowhere to add homebrew ones (yet?)

Yeah, it's super difficult to do due to the invasive nature of most kingdom feats. I had to hard code a lot of stuff. Might be possible in the future.

> Solution 5-1: Allow the Capital to Grow Earlier - If this is implemented, I'm not sure how.

You manage settlements as scenes (check the Kingdom parts of the manual). It's entirely up to you how many blocks you enable your players to build in.

![image](https://github.com/BernhardPosselt/pf2e-kingmaker-tools/assets/195053/55640fef-68ec-4a9c-8333-60f6ffb17fc2)


>  Solution 5-2: Increase the Influence of the Capital at the Lowest Levels - after manual editing of the capital on the kingdom sheet and inspecting the settlement, this does not appear to be implemented.

Influence is not automated, you can just tell your players to increase the radius on the world map by 1

Closing this since I've addressed all of the open questions I hope :)

**Comment by digitalshadowhawk** [comment]
You did, thank you :)

**Comment by BernhardPosselt** [comment]
FYI, I've added a setting on the kingdom sheet to enable the capital investment stuff.
