### ISSUE TITLE
Reconnoiter Hex  and Take Charge activities have multiple display issues

### ISSUE THREAD

**Issue by mgoldstein322** [BernhardPosselt/pf2e-kingmaker-tools#65]
As title says: the Region activity Reconnoiter Hex is currently displayed under Leadership Activities. Additionally, the Take Charge Leadership activity currently displays  "Reconnoiter Hex" as its title when you click the ? button on the right side; Take Charge is also listed as "Reconnoiter Hex" in the "Manage Activities" menu.

Anyways, thanks for this module! It's fantastic and makes running kingmaker much better than with just the official module!

**Comment by BernhardPosselt** [comment]
Fixed, copy paste mistake. Only the title was wrong it seemed.
