### ISSUE TITLE
Add support for homebrew Survival check instead of Cooking Lore to Discover new Recipe

### ISSUE THREAD

**Issue by Cryover** [BernhardPosselt/pf2e-kingmaker-tools#70]

**Comment by BernhardPosselt** [comment]
Have you thought about handing out cooking lore for free?

**Comment by Cryover** [comment]
> Have you thought about house ruling it by just handing out cooking lore for free?

actually yes, but would be really cool if the select input would allow a different check besides only Cooking Lore :<

**Comment by BernhardPosselt** [comment]
You can override camping activities in the latest release by adding one with the same name. In your case, add a new activity with the name "Discover Special Meal" and change the skill to "Survival"
