### ISSUE TITLE
Missing Structure Tokens

### ISSUE THREAD

**Issue by SonofOrion42** [BernhardPosselt/pf2e-kingmaker-tools#72]
For some reason, the token images for the following Kingmaker structures are missing: Bridges, Gladiatorial Arena, Magical Streetlamps, Paved Streets, Sewer System and both Wooden and Stone Walls. I've tried reinstalling the module, but those images are still missing.

**Comment by BernhardPosselt** [comment]
Check the manual, it shows you where you need to place those images.
