### ISSUE TITLE
Assets for missing images

### ISSUE THREAD

**Issue by MarkPearce** [BernhardPosselt/pf2e-kingmaker-tools#76]
[structures.zip](https://github.com/user-attachments/files/16135393/structures.zip)

I created these assets with genAI and some retouching.

The path for the bridge asset shares the same filename. So i changed that to Bridge, Stone.webp and Bridge, Wood.webp

otherwise they all match the paths given.

**Comment by BernhardPosselt** [comment]
What license are those under? Can you check your AI tool?

**Comment by BernhardPosselt** [comment]
Another thing: if the AI was trained using Forgotten Adventure assets, I'm pretty sure that their license would apply here as well which is incompatible with this module's license.

**Comment by MarkPearce** [comment]
I have no insight into the training data, I used mid-journey V6 (standard subscriber)

I provide these for use under CC0 - Public Domain
 https://creativecommons.org/publicdomain/zero/1.0/

**Comment by MarkPearce** [comment]
The path for bridge and bridge, stone still share the same filename. they should be:

pf2e-kingmaker-tools-tokens/structures/Bridge%2C%20Wood.webp
pf2e-kingmaker-tools-tokens/structures/Bridge%2C%20Stone.webp

**Comment by MarkPearce** [comment]
just been reading your house rules, here's one more structure

[Aiudara Gate.zip](https://github.com/user-attachments/files/16152092/Aiudara.Gate.zip)

**Comment by BernhardPosselt** [comment]
> The path for bridge and bridge, stone still share the same filename. they should be:
> 
> pf2e-kingmaker-tools-tokens/structures/Bridge%2C%20Wood.webp pf2e-kingmaker-tools-tokens/structures/Bridge%2C%20Stone.webp

Should not anymore, can you take a look?

**Comment by MarkPearce** [comment]
Images fix'd, but did you mean to set the min version to 12? I haven't updated my server yet, so i tested it on a clone, updated to 12.
.

**Comment by BernhardPosselt** [comment]
Yes, I've been releasing v12 only updates for 2 months. No more support for V11 unfortunately due to API breakage.
