### ISSUE TITLE
Missing Images from Structures

### ISSUE THREAD

**Issue by liquidsonic** [BernhardPosselt/pf2e-kingmaker-tools#77]
![image](https://github.com/user-attachments/assets/b8b52e12-585a-4ada-b080-bb29482a0a46)

Not sure really how to debug this one. 

Seems the new assets I can see by Mark Pearce is in but any other assets are now gone.

**Comment by BernhardPosselt** [comment]
Forge?

Can you inspect where the missing images link to using your browser's html inspector?

**Comment by liquidsonic** [comment]
![image](https://github.com/user-attachments/assets/b438eddc-1a2a-42be-ba27-017239d9ba27)

**Comment by liquidsonic** [comment]
![image](https://github.com/user-attachments/assets/1e2c31ab-c840-4e20-ac69-3522d7e68a05)

**Comment by BernhardPosselt** [comment]
That means you don't have the official kingmaker module enabled, correct?

**Comment by liquidsonic** [comment]
Ahhhhh, right, that might be why!

**Comment by liquidsonic** [comment]
PEBCAK Issue
