### ISSUE TITLE
Weather Events Public Roll

### ISSUE THREAD

**Issue by Pyroman2xxx** [BernhardPosselt/pf2e-kingmaker-tools#80]
I am having an issue where the weather events table roll is not gm-only, though the rolls for weather are.

Player view:
![image](https://github.com/user-attachments/assets/93497d10-0ade-4ad7-9cf6-009901f61da2)

**Comment by BernhardPosselt** [comment]
Can you disable your ui mods?

**Comment by Pyroman2xxx** [comment]
I disabled all mods now except for Kingmaker module and yours, I rolled and got a 20 on the weather events and both are public.
![image](https://github.com/user-attachments/assets/985acc74-b425-4c03-8d6e-dd31e7d29d58)

Player view again:
![image](https://github.com/user-attachments/assets/54add20a-b4a0-496e-ae42-69e9f90af4bf)
