### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Lioheart** [BernhardPosselt/pf2e-kingmaker-tools#83]
Is it possible to translate the core of this module?

**Comment by BernhardPosselt** [comment]
No. Due to how Foundry works, I am unable to really make use of their data types in camping and kingdom sheets. Therefore I need to bundle hard-coded content in the JS executable itself. Translating the module would require me to build custom translation infrastructure which is out of scope.

**Comment by BernhardPosselt** [comment]
I was able to implement translations in the rewrite. See https://github.com/BernhardPosselt/pf2e-kingmaker-tools?tab=readme-ov-file#translations if you want to help translating the module.

**Comment by Lioheart** [comment]
Great, I'll get to work.
