### ISSUE TITLE
Add V&K Leadership Activities

### ISSUE THREAD

**Issue by TALlama** [BernhardPosselt/pf2e-kingmaker-tools#84]
You've got a lot of the V&K optional rules implemented, but you're missing the [**Take Charge** leadership activity](https://docs.google.com/document/d/1NHksCXkXbjtrv-26VgFHNbyYldatVwag9lM44IWxIXo/edit?pli=1&tab=t.0#heading=h.gahvf1ubauvk) and the [**Reconnoiter Hex** leadership activity](https://docs.google.com/document/d/1NHksCXkXbjtrv-26VgFHNbyYldatVwag9lM44IWxIXo/edit?pli=1&tab=t.0#heading=h.wz4a2jvwj8zo). You could fulfill these need with #79; I'm not sure if that's easier.

I'd also love to see your own [Naval Support](https://github.com/BernhardPosselt/pf2e-kingmaker-tools/blob/master/docs/house-rules.md#naval-support) thrown in there!

**Comment by BernhardPosselt** [comment]
You can enable those in the manage activities popup. Should be a button right at the top of the Turn tab.

**Comment by TALlama** [comment]
Ah, I was looking as a user and not the GM, so I didn't see the button. Doesn't seem like `Naval Support` is in there, but we can add it.

Is there any way to have added activities include the buttons that alter RP and commodities and such?

**Comment by BernhardPosselt** [comment]
Simply copy in the button html. You can right click -> Inspect the chat message and go from there.
